# Generated by Django 3.2.11 on 2022-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221103_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dweet',
            name='Img',
            field=models.ImageField(upload_to='profile_img'),
        ),
    ]
