# Generated by Django 3.2.11 on 2022-11-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dweet_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='dweet',
            name='like',
            field=models.ManyToManyField(to='core.Profile'),
        ),
    ]
