# Generated by Django 3.2.11 on 2022-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dweet_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likedweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dweetid', models.CharField(max_length=140)),
                ('profileid', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='dweet',
            name='like',
        ),
        migrations.AddField(
            model_name='dweet',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
